<!DOCTYPE html>
<html>
<head>
    <title>Add Employee</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

<div class="container">
    <h1 class="mt-5">Employee Creator</h1>
    <form method="post" action="/iwq/src/public/employee/add">
        <div class="form-group">
            <label for="firstName">Imię:</label>
            <input type="text" class="form-control" id="firstName" name="firstName" placeholder="Wpisz imię">
        </div>
        <div class="form-group">
            <label for="lastName">Nazwisko:</label>
            <input type="text" class="form-control" id="lastName" name="lastName" placeholder="Wpisz nazwisko">
        </div>
        <div class="form-group">
            <label for="address">Adres:</label>
            <input type="text" class="form-control" id="address" name="address" placeholder="Wpisz adres">
        </div>
        <div class="form-group">
            <label for="pesel">PESEL:</label>
            <input type="number" class="form-control" id="pesel" name="pesel" placeholder="Wpisz numer PESEL">
        </div>
        <button type="submit" name="addEmployee" class="btn btn-success">Dodaj</button>
        <a href="/iwq/src/public/employees" class="btn btn-primary">Powrót</a>
    </form>
</div>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>