<!DOCTYPE html>
<html>
<head>
    <title>Employee Update</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>

<div class="container">
    <h1 class="mt-5">Employee Update</h1>
    <form method="post" action="/iwq/src/public/employee/update/<?php echo $data[0]['pesel']; ?>">
        <div class="form-group">
            <label for="firstName">Imię:</label>
            <input type="text" class="form-control" id="firstName" <?php echo 'value="' . $data[0]['imie'] . '"'; ?> name="firstName" placeholder="Wpisz imię">
        </div>
        <div class="form-group">
            <label for="lastName">Nazwisko:</label>
            <input type="text" class="form-control" id="lastName" <?php echo 'value="' . $data[0]['nazwisko'] . '"'; ?> name="lastName" placeholder="Wpisz nazwisko">
        </div>
        <div class="form-group">
            <label for="address">Adres:</label>
            <input type="text" class="form-control" id="address" <?php echo 'value="' . $data[0]['adres'] . '"'; ?> name="address" placeholder="Wpisz adres">
        </div>
        <div class="form-group">
            <label for="pesel">PESEL:</label>
            <input type="number" disabled class="form-control" id="pesel" <?php echo 'value="' . $data[0]['pesel'] . '"'; ?> name="pesel" placeholder="Wpisz numer PESEL">
        </div>
        <button type="submit" name="updateEmployee" class="btn btn-success">Aktualizuj</button>
        <a href="/iwq/src/public/employees" class="btn btn-primary">Powrót</a>
    </form>
</div>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>